name = "hugo-lamp-plus"
license = "MIT"
licenselink = "https://github.com/chabad360/hugo-lamp-plus/blob/master/LICENSE.md"
description = "A light, responsive Hugo theme for blogs"
homepage = "https://github.com/chabad360/hugo-lamp-plus"
tags = ["hugo", "blog", "theme", "responsive"]
features = ["Blog", "Responsive", "Search"]
min_version = "extended_0.53.3"

[author]
  name = "Mendel Greenberg"
  homepage = "https://chabad360.me/page/about-me"
