env:
  - HUGO=0.58.3

install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v$HUGO/hugo_$HUGO_Linux-64bit.deb
  - sudo dpkg -i hugo_0.55.4_Linux-64bit.deb
  
script:
  - hugo
  
deploy:
  provider: pages:git
  token: $PAGES_TOKEN
  repo: chabad360/chabad360.github.io
  target_branch: master
  fqdn: chabad360.me
  verbose: true
  edge: true # opt in to dpl v2
