language: ruby
cache: bundler
rvm:
  - dpl
  - octokit
  - public_suffix
  - sitemap-parser
  - http

env:
  global:
    - HUGO=0.58.3

install:
  - curl -LO "https://github.com/gohugoio/hugo/releases/download/v${HUGO}/hugo_extended_${HUGO}_Linux-64bit.deb"
  - sudo dpkg -i hugo*.deb
  - hugo version

script:
  - hugo

deploy:
  provider: pages:git
  token: $GITHUB_TOKEN
  repo: "chabad360/chabad360.github.io"
  target_branch: "master"
  fqdn: "chabad360.me"
  verbose: true
  cleanup: false
  local_dir: "public"
  edge: true

after_deploy:
  - ruby purge_cache.rb