baseURL: "https://chabad360.me/"
enableRobotsTXT: true
googleAnalytics: "UA-147634698-1"
languageCode: "en-us"

theme: "hugo-lamp"
title: "Mendel Greenberg"

markup:
  highlight:
    codeFences: true
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: false
    tabWidth: 2


menu:
  main:
    - name: "Posts"
      url: "/post/"
      weight: 1

    - identifier: "projects"
      name: "Projects"
      url: "/project/"
      weight: 3

    - identifier: "tags"
      name: "Tags"
      url: "/tags/"
      weight: 4

author:
  name: "Mendel Greenberg"
  email: "mendel@chabad360.me"

params:
  author: "Mendel Greenberg"
  description: "Different things I've done, tried, or found interesting enough to blog about."
  keywords: "chabad360,blog,developer,personal"
  email: "mendel@chabad360.me"
  avatarurl: "/img/avatar.jpg"
  seotitle: "Mendel Greenberg (aka chabad360)"
  subtitle: "(aka chabad360)"

  search: true
  mainSections: ["posts"]
  paginate: 25
  showComments: true

  since: "2020"

  colorscheme: "dark"

  social:
    - name: "Github"
      icon: "fab fa-github"
      weight: 1
      url: "https://github.com/chabad360/"

    - name: "Gitlab"
      icon: "fab fa-gitlab"
      weight: 2
      url: "https://gitlab.com/chabad360/"

    - name: "Reddit"
      icon: "fab fa-reddit"
      weight: 3
      url: "https://reddit.com/u/chabad360/"

    - name: "Email"
      icon: "fas fa-at"
      weight: 4
      url: "mailto:mendel@chabad360.me"

    - name: "Feed"
      icon: "fas fa-rss"
      weight: 5
      url: "https://chabad360.me/index.xml"

taxonomies:
  tag: "tags"

outputs:
  home:
  - HTML
  - JSON
  - RSS
  page:
  - HTML