baseURL = "https://chabad360.me/"
languageCode = "en-us"
title = "Mendel Greenberg"
theme = "hugo-lamp"

enableRobotsTXT = true

DefaultContentLanguage = "en"

googleAnalytics = "UA-147634698-1"

disqusShortname = "chabad360-me"

# Code highlighting
pygmentsUseClasses=true
linenos=true
pygmentsCodeFences=true

[params]
  mainSections = ["posts"]
  subtitle = "(aka chabad360)"
  author = "Mendel Greenberg"
  logo = "/img/avatar.jpg"
#  description = "A light responsive Hugo AMP theme for blogger"
  paginate = 10

  # SEO configs
  seotitle = "Mendel Greenberg (aka chabad360)"

  # Page configs
  showComments = true

  # Search configs
  algolia_search = true
  algolia_appId = "PGM2NJXWVH"
  algolia_apiKey = "f65b57ce60ed335aedc88844faab7cc2"
  algolia_indexName = "chabad360.me"

  # Social networks
  email = "mendel@chabad360.me"
  github = "chabad360"
  reddit = "chabad360"

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "author"

#[[menu.main]]
#  name = "Tags"
#  weight = 2
#  identifier = "tags"
#  url = "/tags/"

[[menu.main]]
  name = "About Me"
  weight = 1
  identifier = "about-me"
  url = "/page/about-me"

[outputs]
  home = [ "HTML", "JSON", "RSS" ]
  page = [ "HTML" ]