DefaultContentLanguage = "en"
baseURL = "https://chabad360.me/"
enableRobotsTXT = true
googleAnalytics = "UA-147634698-1"
languageCode = "en-us"
linenos = true
pygmentsCodeFences = true
pygmentsUseClasses = true
theme = "hugo-lamp"
title = "Mendel Greenberg"
[[menu.main]]
name = "Posts"
url = "/"
weight = 1
[[menu.main]]
name = "About Me"
url = "/page/about-me"
weight = 2
[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/project/"
weight = 3
[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 4
[params]
author = "Mendel Greenberg"
description = "Different things I've done, tried, or found interesting enough to blog about."
email = "mendel@chabad360.me"
github = "chabad360"
googleCseId = "006958833182019350199:fiwtwuvmck8"
logo = "/img/avatar.jpg"
mainSections = ["posts"]
paginate = 10
reddit = "chabad360"
seotitle = "Mendel Greenberg (aka chabad360)"
showComments = true
subtitle = "(aka chabad360)"
[taxonomies]
category = "categories"
tag = "tags"
