---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: Title
- type: file
  name: cover
  label: Cover Image
- type: datetime
  name: date
  label: Date
  config:
    required: true
    export_format: YYYY-MM-DDThh:mm:ssZZ
  default: now
