---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: Title
- type: file
  name: cover
  label: Cover Image
- type: text
  name: project
  label: Project Name
  config:
    required: true
  description: "(Can be same a Title)"
- type: datetime
  name: date
  label: Date
  config:
    required: true
  default: now
