---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: Title
- type: file
  name: cover
  label: Cover Image
- name: tags
  type: tag_list
  default: []
  label: Tags
  description: tags
- type: datetime
  name: date
  label: Date
  config:
    required: true
    export_format: YYYY-MM-DDThh:mm:ss
  default: now
- name: project
  type: text
  config:
    required: true
  label: Project Code Name
  description: An easy to write name to reference this project by.
