name: "Build Site"

on:
  push:
    branches:
      - build

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v1.2.0
        with:
          submodules: true
        
      - name: "Compress Images"
        uses: chabad360/image-actions@master
        with:
          ignorePaths: "themes/**"
        
      - name: "Publish Site"
        uses: chabad360/hugo-gh-pages@master
        with:
          branch: "master"
          cname: "chabad360.me"
          githubToken: ${{ secrets.PERSONAL_TOKEN }}

      - name: "Purge Cloudflare Cache"
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_KEY }}
