name: Hugo Build

on:
  push:
    branches:
    - build

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    
    steps:
    - name: Checkout Repo
      uses: actions/checkout@master
      with:
        submodules: true
        
    - name: Publish Site
      uses: chabad360/hugo-to-gh-pages@master
      with:
        args: --gc --minify --cleanDestinationDir
      env:
        BRANCH: master
        CNAME: chabad360.me
        GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

    - name: Purge Cloudflare Cache
      uses: jakejarvis/cloudflare-purge-action@master
      env:
        CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
        CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
        CLOUDFLARE_KEY: ${{ secrets.CLOUDFLARE_KEY }}
