name: "Build Site test"

on:
  push:
    branches:
      - build

jobs:
  build-deploy-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@master
        with:
          submodules: true
      
      - name: "Compress IMG"
        uses: chabad360/image-actions@master
        with:
          ignorepaths: "themes/**"
        
      - name: "Build Site"
        uses: chabad360/hugo-actions@master
        
      - name: "Test HTML"
        uses: chabad360/htmlproofer@master
        with:
          directory: "./public"
